name: directus_api_manager
description: Communicate with a Directus server using its REST API.
version: 1.15.0
repository: https://github.com/maxbritto/directus_api_manager

environment:
     sdk: ^3.5.3

dependencies:
     http: ">=0.13.4 <2.0.0"
     http_parser: ">=4.0.0 <5.0.0"
     reflectable: ^5.1.0
     web_socket_channel: ^3.0.3
     extension_dart_tools: ^1.4.1
     meta: "^1.15.0"
     mutex: ^3.1.0

dev_dependencies:
     build_runner: any
     reflectable_builder: ^1.1.0
     lints: ^6.0.0
     test: ^1.27.0

targets:
     $default:
          builders:
               reflectable:
                    generate_for:
                         - example/directus_api_manager_example.dart
                    options:
                         formatted: true
