import 'package:directus_api_manager/src/generator/directus_schema_fetcher.dart';
import 'package:directus_api_manager/src/generator/field_type_mapper.dart';

/// Generates Dart entity class source code from Directus schema information.
class EntityClassGenerator {
  static const String generatedFileHeader =
      "// GENERATED CODE - DO NOT MODIFY BY HAND";

  final String classSuffix;
  final bool generateReadonlySetters;

  EntityClassGenerator({
    this.classSuffix = "DirectusModel",
    this.generateReadonlySetters = false,
  });

  /// Generates a complete Dart file for a Directus collection.
  String generateClassFile({
    required DirectusCollectionInfo collection,
    required List<DirectusFieldInfo> fields,
    required List<DirectusRelationInfo> relations,
  }) {
    final buffer = StringBuffer();
    final collectionName = collection.collection;
    final className = _collectionToClassName(collectionName);

    // Header
    buffer.writeln(generatedFileHeader);
    buffer.writeln(
        "// Generated by directus_api_manager entity generator");
    buffer.writeln("// Source collection: $collectionName");
    buffer.writeln();

    // Import
    buffer.writeln(
        "import 'package:directus_api_manager/directus_api_manager.dart';");
    buffer.writeln();

    // Annotations
    buffer.writeln("@DirectusCollection()");
    buffer.writeln(
        '@CollectionMetadata(endpointName: "$collectionName")');

    // Class declaration
    buffer.writeln("class $className extends DirectusItem {");

    // Constructors
    buffer.writeln("  $className(super.rawReceivedData);");
    buffer.writeln("  $className.newItem() : super.newItem();");
    buffer.writeln();

    // Separate fields into regular fields and relation-only fields
    final regularFields = fields
        .where((f) =>
            !f.isPrimaryKey &&
            !f.isAlias &&
            !f.isOneToMany &&
            !f.isManyToMany)
        .toList();

    // Generate key constants
    if (regularFields.isNotEmpty) {
      buffer.writeln("  // --- Field Keys ---");
      for (final field in regularFields) {
        final constantName = _fieldToKeyConstant(field.field);
        buffer.writeln(
            '  static const String $constantName = "${field.field}";');
      }
      buffer.writeln();
    }

    // Generate properties
    if (regularFields.isNotEmpty) {
      buffer.writeln("  // --- Properties ---");
      buffer.writeln();

      for (final field in regularFields) {
        _generateFieldProperty(buffer, field, relations);
      }
    }

    // Add comments for O2M and M2M relations
    final relationFields =
        fields.where((f) => f.isOneToMany || f.isManyToMany).toList();
    if (relationFields.isNotEmpty) {
      buffer.writeln("  // --- Relations (not directly accessible as properties) ---");
      for (final field in relationFields) {
        final relationType = field.isOneToMany ? "One-to-Many" : "Many-to-Many";
        final relatedCollection = _findRelatedCollection(
            field.collection, field.field, relations);
        buffer.writeln(
            "  // ${field.field}: $relationType relation${relatedCollection != null ? " -> $relatedCollection" : ""}");
      }
      buffer.writeln();
    }

    // Close class
    buffer.writeln("}");

    return buffer.toString();
  }

  void _generateFieldProperty(
    StringBuffer buffer,
    DirectusFieldInfo field,
    List<DirectusRelationInfo> relations,
  ) {
    final propertyName = _fieldToPropertyName(field.field);
    final keyConstantName = _fieldToKeyConstant(field.field);
    final isReadonly = field.isReadonly || field.field == "id";

    // Determine if this is a file relation
    final isFileRelation = field.isFileRelation;

    // For M2O relations (non-file), generate a simple String id getter
    if (field.isManyToOne) {
      final relatedCollection = _findRelatedCollection(
          field.collection, field.field, relations);

      final dartType = field.isNullable ? "String?" : "String";
      buffer.writeln(
          "  /// ${field.field} (relation M2O${relatedCollection != null ? " -> $relatedCollection" : ""})");
      buffer.writeln(
          "  $dartType get $propertyName => getValue(forKey: $keyConstantName);");
      if (!isReadonly || generateReadonlySetters) {
        buffer.writeln(
            "  set $propertyName($dartType value) => setValue(value, forKey: $keyConstantName);");
      }
      buffer.writeln();
      return;
    }

    // Map type
    final typeInfo = FieldTypeMapper.mapFieldType(
      directusType: field.type ?? "string",
      isNullable: field.isNullable,
      isFileRelation: isFileRelation,
    );

    // Comment
    final requiredLabel = field.isRequired ? "required" : "optional";
    final readonlyLabel = isReadonly ? ", readonly" : "";
    buffer.writeln(
        "  /// ${field.field} (${field.type ?? "unknown"}, $requiredLabel$readonlyLabel)");

    // Getter
    final getterCode = FieldTypeMapper.generateGetter(
      propertyName: propertyName,
      fieldKey: field.field,
      typeInfo: typeInfo,
      keyConstantName: keyConstantName,
    );
    buffer.writeln("  ${typeInfo.dartType} get $getterCode;");

    // Setter (unless readonly)
    if (!isReadonly || generateReadonlySetters) {
      final setterCode = FieldTypeMapper.generateSetter(
        propertyName: propertyName,
        fieldKey: field.field,
        typeInfo: typeInfo,
        keyConstantName: keyConstantName,
      );
      if (setterCode != null) {
        buffer.writeln("  set $setterCode;");
      }
    }

    buffer.writeln();
  }

  /// Converts a collection name (snake_case) to a Dart class name (PascalCase).
  String _collectionToClassName(String collectionName) {
    final parts = collectionName.split("_");
    final pascalCase = parts
        .map((part) =>
            part.isEmpty ? "" : part[0].toUpperCase() + part.substring(1))
        .join();
    return "$pascalCase$classSuffix";
  }

  /// Converts a field name (snake_case) to a Dart property name (camelCase).
  String _fieldToPropertyName(String fieldName) {
    final parts = fieldName.split("_");
    if (parts.isEmpty) return fieldName;
    final first = parts.first;
    final rest = parts.skip(1).map((part) =>
        part.isEmpty ? "" : part[0].toUpperCase() + part.substring(1));
    return first + rest.join();
  }

  /// Converts a field name to a key constant name (camelCase + "Key").
  String _fieldToKeyConstant(String fieldName) {
    return "${_fieldToPropertyName(fieldName)}Key";
  }

  /// Generates a file name for the given collection.
  String generateFileName(String collectionName) {
    return "${collectionName}_directus_model.dart";
  }

  /// Finds the related collection for a given field via the relations list.
  String? _findRelatedCollection(
    String collection,
    String field,
    List<DirectusRelationInfo> relations,
  ) {
    for (final relation in relations) {
      if (relation.collection == collection && relation.field == field) {
        return relation.relatedCollection;
      }
    }
    return null;
  }
}
