import 'package:directus_api_manager/directus_api_manager.dart';

abstract class DirectusData {
  final Map<String, dynamic> _rawReceivedData;
  final Map<String, dynamic> updatedProperties = {};

  DirectusData(this._rawReceivedData) {
    if (!_rawReceivedData.containsKey("id")) {
      throw Exception("id is required");
    }
  }

  DirectusData.newDirectusData([this._rawReceivedData = const {}]);

  /// Returns the id of the item
  /// We respect directus recommandations of having an [id] field for each collection.
  /// It can be null because a new item can be created without an id and will get its id generated by the server
  /// If you fetched the item from the server, it will have an id and it will certainly never be null
  String? get id {
    dynamic idData = getValue(forKey: "id");
    if (idData is int) {
      return idData.toString();
    }

    return idData;
  }

  Map<String, dynamic> getRawData() => _rawReceivedData;
  bool get needsSaving => updatedProperties.isNotEmpty;

  setValue(dynamic value, {required String forKey}) {
    if (value != getValue(forKey: forKey)) {
      updatedProperties[forKey] = value;
    }
  }

  dynamic getValue({required String forKey}) {
    return updatedProperties.containsKey(forKey)
        ? updatedProperties[forKey]
        : _rawReceivedData[forKey];
  }

  DirectusFile getDirectusFile({required String forKey}) {
    final dynamic value = getOptionalDirectusFile(forKey: forKey);
    assert(value != null);
    return value;
  }

  DirectusFile? getOptionalDirectusFile({required String forKey}) {
    final dynamic value = getValue(forKey: forKey);
    if (value is Map<String, dynamic>) {
      return DirectusFile.fromJSON(value);
    }
    return null;
  }

  /// returns a map of all the properties of the item merged with the ones that have been updated
  Map<String, dynamic> toMap() {
    return Map<String, dynamic>.of(_rawReceivedData)..addAll(updatedProperties);
  }
}

extension DirectusDataExtension on DirectusData {
  /// Returns a map of all the properties of the item without the id that must not be sent to the server when creating a new item
  Map<String, dynamic> mapForObjectCreation() {
    return toMap()..remove("id");
  }
}
